### ISSUE TITLE
Ideas.

### ISSUE THREAD

**Issue by TheIntelloBox** [RayzrDev/PrisonPicks#1]
Hey,

I hope you remember me, I was helping you on DecoHeads. I have suggestions:

For the explosive pickaxe: 
- PerWorld support.
- WorldGuard region support.
- Blacklist support.
- Something to prevent the player to destroy what other players build.

**Comment by AlexanderBeck0** [comment]
@TheIntelloBox I like that idea a lot. Also, maybe include a system where you can level up the pickaxe and have leaderboards? That would be cool.

**Comment by TheIntelloBox** [comment]
Yeah that would be fantastic, for example the man who breaks the most blocks, etc. Maybe a command for the admin : /explosivepickaxe setradius 10 for example.

**Comment by I-Al-Istannen** [comment]
* WorldGuard is supported for the `Explosive pickaxe`, if it doesn't work, I'd file a bug report.
* I'd argue that you should let a proper stats plugin take care of tracking block breaks and a leaderboard.
* WorldGuard can already stop you from destroying things other people built, unless they break things using the `Bountiful pickaxe`, which doesn't respect world guard. Though having a house made from Diamond ore is probably not that likely.

* Region support means you want it to work in given world guard regions only or the other way round?
* You already need to whitelist blocks for the `Smelters` and `Bountiful pickaxe`, so I guess a blacklist for the `Explosive pickaxe` is what you are after?

* Would that command apply to all pickaxes or only the one you are holding? In the latter case a config setting is maybe nicer to work with. [@TheIntelloBox ]

**Comment by TheIntelloBox** [comment]
Or maybe a shop to buy upgrades for the explosive pickaxe. For example, Tier 1 = radius of 4 blocks, Tier 2 : radius of 5 blocks, etc.

**Comment by foxfirecodes** [comment]
- Per-world support is also definitely something I would love to add.
- WorldGuard region support is definitely something I will add, that sounds like a great idea.
- Blacklist support - is this meant to be a list of blocks the explosive pickaxe *can't* break?
- Something to prevent the player from destroying what other players build would be a nice feature, but it would be very difficult to implement and it would also be slightly irrelevant as this is a plugin meant for Prison servers. Usually people don't build in Prison servers :P
- A radius config option for the explosive pickaxe would also be relatively easy to add and be a very nice feature.

As for the leveling up and all that, I do not believe that has a place in this plugin, it goes a bit outside the scope of what the original requester wanted.

**Comment by TheIntelloBox** [comment]
Hi ! :D 

"Blacklist support - is this meant to be a list of blocks the explosive pickaxe can't break?".
Exactly ! :D 

"As for the leveling up and all that, I do not believe that has a place in this plugin, is it goes a bit outside the scope of what the original requester wanted."
Or you can add a command, for example /prisonpicks setradius number. :D 

Thanks ! :D

**Comment by foxfirecodes** [comment]
* Per world support added in `2ac4de6dd442bf72936a44cf6cf7b04877e4fede`.
* Explosive pickaxe blacklist added in `543db9e35c4ec24b4f22cc8a9efea55a111b1d47`.
* Explosive pickaxe configurable radius added in `a48167218ee8e3e8d6b3941833cc846ff015a4f0`.

You can get the latest builds on the [build server](https://ci.rayzr.tech/job/PrisonPicks).

**Comment by TheIntelloBox** [comment]
Hi,

Build server is down. :x Release it on GitHub maybe ?

**Comment by foxfirecodes** [comment]
Strange, the build server appears to be working for me now. I'm not going to release on GitHub since it is not fully completed yet. However, if this continues to be an issue, I can directly post a compiled JAR file here.

**Comment by foxfirecodes** [comment]
All other features but WorldGuard Region Support have been implemented. I have moved that to a separate issue for organizational purposes. See #5 for more information.
