### ISSUE TITLE
1.13 Update.

### ISSUE THREAD

**Issue by TheIntelloBox** [RayzrDev/PrisonPicks#4]
Hey ! :D 

I think that the plugin will break with the 1.13 update. :D 
So I open this issue, you can close it if the plugin doesn't break or if you fixed the problems with the 1.13 update. :D 

Thanks ! :D 
TheIntelloBox. :D

**Comment by foxfirecodes** [comment]
Why would PrisonPicks break with 1.13?

**Comment by TheIntelloBox** [comment]
Because 1.13 changes many many many things. :D

**Comment by I-Al-Istannen** [comment]
The cool thing about bukkit is that it offers an API abstraction layer *independent of the inner workings*. So many updates will not do anything, some plugins written for ancient version still do just fine. Only when you start to use newer features or get quite … _creative_ things generally just work.

Something that actually broke some plugins was the offhand (as suddenly two things could interact simultaneously).

So I'd probably just wait and see, but the code doesn't seem too adventurous.

Haven't tried it though, this is just intended as a general heads up to explain his question. Some testing will be needed anyways :)
